services:
  ayla-bridge:
    container_name: ayla-bridge
    build: .
    environment:
      - BIND_IP=192.168.1.8
      - BIND_PORT=10275
      - DEVICES_PATH=./devices.json
    volumes:
      - ./json/devices.json:/app/src/devices.json:ro
    network_mode: host
    restart: unless-stopped
